name: release_github

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after build'
        required: true
        default: 'no'
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_PYTHON_VERSION: 3.10
  PACKAGE_NAME: evernote-backup
  MODULE_NAME: evernote_backup

jobs:
  build_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v9

      - name: Export requirements
        run: uv pip compile pyproject.toml -q --universal --no-annotate --no-header -o requirements.txt

      - name: Get Git commit timestamp
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Build project for distribution
        run: uv build
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Save release python requirements
        uses: actions/upload-artifact@v7
        with:
          name: release_dist_reqs
          path: requirements.txt

      - name: Save release python packages
        uses: actions/upload-artifact@v7
        with:
          name: release_dist_python
          path: dist

  build_binaries:
    needs: build_python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            OS_CODE: macos_intel
            OS_CODE_BASE: macos
          - os: macos-15
            OS_CODE: macos
            OS_CODE_BASE: macos
          - os: ubuntu-latest
            OS_CODE: linux
            OS_CODE_BASE: linux
          - os: ubuntu-24.04-arm
            OS_CODE: linux_arm
            OS_CODE_BASE: linux
          - os: windows-latest
            OS_CODE: win
            OS_CODE_BASE: win
          - os: windows-11-arm
            OS_CODE: win_arm
            OS_CODE_BASE: win

    steps:
      - uses: actions/checkout@v7

      - name: Get version
        if: ${{ startsWith(matrix.os, 'macos-') }}
        shell: bash
        run: |
          APP_VERSION=$(perl -n -e'/^__version__ = "([^"]+)"$/ && print $1' ${{ env.MODULE_NAME }}/version.py)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Get version
        if: ${{ ! startsWith(matrix.os, 'macos-') }}
        shell: bash
        run: |
          APP_VERSION=$(sed -n 's/^__version__ = "\([^"]\+\)"$/\1/p' ${{ env.MODULE_NAME }}/version.py)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Load release python requirements
        uses: actions/download-artifact@v8
        with:
          name: release_dist_reqs

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller ${{ env.PACKAGE_NAME }}.spec

      - name: Make directory for bins
        run: mkdir dist_bin

      - name: Pack up binary for macos arm64
        if: matrix.OS_CODE == 'macos'
        run: zip -q -j dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_arm64.zip ./dist/${{ env.PACKAGE_NAME }}

      - name: Pack up binary for macos x64
        if: matrix.OS_CODE == 'macos_intel'
        run: zip -q -j dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_x64.zip ./dist/${{ env.PACKAGE_NAME }}

      - name: Pack up binary for linux
        if: matrix.OS_CODE == 'linux'
        run: tar -zcvf dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_x64.tar.gz -C ./dist ${{ env.PACKAGE_NAME }}

      - name: Pack up binary for linux arm64
        if: matrix.OS_CODE == 'linux_arm'
        run: tar -zcvf dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_arm64.tar.gz -C ./dist ${{ env.PACKAGE_NAME }}

      - name: Pack up binary for windows
        if: matrix.OS_CODE == 'win'
        run: |
          choco install zip
          zip -q -j dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_x64.zip ./dist/${{ env.PACKAGE_NAME }}.exe

      - name: Pack up binary for windows arm64
        if: matrix.OS_CODE == 'win_arm'
        run: |
          choco install zip
          zip -q -j dist_bin/bin_${{ env.MODULE_NAME }}_${{ env.APP_VERSION }}_${{ matrix.OS_CODE_BASE }}_arm64.zip ./dist/${{ env.PACKAGE_NAME }}.exe

      - name: Save release binaries for ${{ matrix.OS_CODE }}
        uses: actions/upload-artifact@v7
        with:
          name: release_dist_bin_${{ matrix.OS_CODE }}
          path: dist_bin

  release:
    if: github.event_name == 'push' || github.event.inputs.release == 'yes'
    needs: [ build_binaries ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Extract release changelog
        run: |
          sed "0,/## \[/d;/## \[/Q" CHANGELOG.md > release_changelog
          echo -n "**Full Changelog**: " >> release_changelog
          sed -n 's/## \[.*\](\(.*\)) (.*/\1/p' CHANGELOG.md | head -1 >> release_changelog

      - name: Get tag version
        run: |
          APP_VERSION=$(sed -n 's/^__version__ = "\([^"]\+\)"$/\1/p' ${{ env.MODULE_NAME }}/version.py)
          echo "TAG_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Load release python packages
        uses: actions/download-artifact@v8
        with:
          name: release_dist_python
          path: dist

      - name: Load release binaries for linux
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_linux
          path: dist

      - name: Load release binaries for linux arm64
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_linux_arm
          path: dist

      - name: Load release binaries for windows
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_win
          path: dist

      - name: Load release binaries for windows arm64
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_win_arm
          path: dist

      - name: Load release binaries for macos arm64
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_macos
          path: dist

      - name: Load release binaries for macos x64
        uses: actions/download-artifact@v8
        with:
          name: release_dist_bin_macos_intel
          path: dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release_changelog
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_VERSION }}
          draft: true
