name: tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '**.py'
      - 'tests/**'
      - 'uv.lock'
      - '.github/workflows/test.yml'
      - '!**/version.py'

env:
  PACKAGE_NAME: evernote_backup

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15, macos-15-intel ]
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        exclude:
          # Python 3.10 is not available for Windows ARM64
          - os: windows-11-arm
            python-version: "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Load cached venv
        id: cached-dependencies
        uses: actions/cache@v6
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: uv sync --frozen --all-groups

      - name: Run tests
        shell: bash
        run: uv run --frozen pytest --cov-report=xml --cov=${{ env.PACKAGE_NAME }} tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        if: matrix.os == 'windows-latest' && matrix.python-version == '3.14'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
